version: "3.9"

services:
  traefik:
    image: traefik:v3.1
    command:
      - --entrypoints.traefik.address=:9099
      - --entrypoints.web.address=:888
      - --entrypoints.websecure.address=:444
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --certificatesresolvers.le.acme.email=${ACME_EMAIL}  
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --api.dashboard=true
      - --log.level=INFO
    ports:
      - target: 888
        published: 888
        protocol: tcp
        mode: host
      - target: 444
        published: 444
        protocol: tcp
        mode: host
      - target: 9099
        published: 9099
        protocol: tcp
        mode: host
    volumes:
      - traefik_letsencrypt:/letsencrypt   # <-- on garde seulement ACME en volume
    configs:
      - source: traefik_middlewares
        target: /etc/traefik/dynamic/middlewares.yml
      - source: traefik_routes
        target: /etc/traefik/dynamic/routers-services.yml
    networks: [ edge ]
    deploy:
      replicas: 1
      restart_policy: { condition: any }
      placement:
        constraints:
          - node.role == manager

volumes:
  traefik_letsencrypt: {}

configs:
  traefik_middlewares:
    file: ./dynamic/middlewares.yml
  traefik_routes:
    file: ./dynamic/routers-services.yml

networks:
  edge:
    driver: overlay
    attachable: true
