## static configuration

global:
  # Send anonymous usage data
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
  ping:
    address: ":8082"

# Access logs
accessLog:
  fields:
    headers:
      names:
        User-Agent: keep

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      httpChallenge:
        entrypoint: web
      email: charettedavid@gmail.com
      storage: /etc/traefik/acme/acme.json

ping:
  entryPoint: "ping"

api:
  dashboard: true

log:
  level: INFO