tcp:
  routers:
    closingthegap-passthrough:
      # Toutes les requêtes TLS dont le SNI matche *.eboutique.asdpromo.com
      rule: "HostSNI(`shop.closingthegap.ca`)"
      entryPoints: ["websecure"]
      service: iis443-ctg
      tls:
        passthrough: true

  services:
    iis443-ctg:
      loadBalancer:
        servers:
          - address: "192.168.8.143:443"